# xrandr cannot find the 144 hz refresh rate default
Section "Monitor"
    Identifier "DP-1"
    Modeline "3440x1440_144.00_rb" 782.12 3440 3448 3480 3520 1440 1529 1537 1543 +hsync -vsync
    Option "PreferredMode" "3440x1440_144.00_rb"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "YourGPU"
    Monitor "DP-1"
    DefaultDepth 24
    SubSection "Display"
        Modes "3440x1440_144.00_rb"
    EndSubSection
EndSection

Section "Device"
    Identifier "RTX3070"
    Driver "nvidia"
EndSection
