#!/bin/bash

STEP=5

case "$BLOCK_BUTTON" in
    4)
        wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.05+
        ;;
    5)
        wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.05-
        ;;
    3)
        wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
        ;;
esac

volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)

if [[ "$volume" == *"[MUTED]"* ]]; then
    echo "VOL: MUTE"
else
    percentage=$(awk '{printf "%.0f", $2 * 100}' <<< "$volume")
    echo "VOL: ${percentage}%"
fi
